### ISSUE TITLE
bug: footer stays on the page while scrolling

### ISSUE THREAD

**Issue by corentinnormand** [wiremock/wiremock.org-sources#1]
The footer of the https://wiremock.org/docs/api/ webpage is kept in place while scrolling, which kind of hinders the ability to see the documentation for the first entry, see screenshot.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/30508927/172222459-3e12dcb2-1f92-4bc6-899f-d195c5d6234c.png">

Found this bug on the macbook pro M1 on firefox, google chrome & safari.

**Comment by oleg-nenashev** [comment]
Hi @corentinnormand . Better late than never, thanks for the report! I checked it, and I cannot reproduce it on the latest Chrome/Firefox - amd64/Windows versions. Most likely one of the updates solved it. I would appreciate if you could check it on MacBook M1/M2, just in case.

P.S: The page's rendering remains really bad though. Some updates are needed

**Comment by corentinnormand** [comment]
It is indeed fixed ! I'll close the issue
